### PR TITLE
NEWS for 3.1 rectified

### PR DESCRIPTION
**Pull request by Olf0**
Rectified typos and wording in NEWS file for Gpg4win 3.1, especially German strings.

### CODE REVIEW

**Comment by AndreHeinecke** [comment]
Thanks. I've applied this with rev. 9ad8eaf
But please note that I only saw this pull request because you notified me in Jabber about this.
Github repos for the GnuPG projects are unofficial and pull requests here are generally not seen by the GnuPG-Developers.

**Comment by Olf0** [comment]
Hmmm, I expected some technical maintainer(s) of this Gpg4win repository on Github to receive an email, when a new PR is submitted.

Well, I chose this route, because it posed the lowest hurdle to enhance the NEWS section for 3.1 quickly:
Just a click to clone the repo, alter the text in the online editor, click for submitting a PR, done.

In contrast to that *diffusion* seems to enforce cloning a repository to a local device, changing the files there and submit a PR via *git* command.

This is an additional and somewhat artificial hurdle for contributors, which IMO should be avoided (in order to attract as many contributions as possible).

Specifically this contribution was created on a phone.  I avoided using *git* on my phone (although technically feasible) so far and do not intend to change that.  Consequently enforcing the use of *git* severely restricts when and where I can create such PRs.

Any ideas on how to handle this in the future?

**Comment by AndreHeinecke** [comment]
Editing files in the browser is already on the wishlist for phabricator https://secure.phabricator.com/T6008  And yes. github is convenient. But for Gpg4win / GnuPG Projects we don't use it anyway ;-)

As your usecase of creating a Patch on the phone is fairly unique it would be ok with me if in the future you would still create a pull request here and give me (or Jochen) a ping. I'm also watching the repository now so I might see a notification.

Easiest for me would be if you would just send the modified NEWS as a file per Mail. This is also how I get changes from translators.

**Comment by Olf0** [comment]
O.K.

**Pull request closed without merging**
